include: package:very_good_analysis/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations:
      injection.config.dart: false