// ignore_for_file: unused_import

import 'package:get_it/get_it.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'package:injectable/injectable.dart';
import 'package:interpretasi/injection.config.dart';
import 'package:interpretasi/src/data/datasources/article_data_source.dart';
import 'package:interpretasi/src/data/datasources/auth_data_source.dart';
import 'package:interpretasi/src/data/datasources/author_data_source.dart';
import 'package:interpretasi/src/data/datasources/boarding_data_source.dart';
import 'package:interpretasi/src/data/datasources/category_data_source.dart';
import 'package:interpretasi/src/data/datasources/comment_article_data_source.dart';
import 'package:interpretasi/src/data/datasources/like_article_data_source.dart';
import 'package:interpretasi/src/data/datasources/password_data_source.dart';
import 'package:interpretasi/src/data/datasources/user_article_data_source.dart';
import 'package:interpretasi/src/data/datasources/user_data_source.dart';
import 'package:interpretasi/src/data/repositories/article_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/auth_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/author_data_source_impl.dart';
import 'package:interpretasi/src/data/repositories/boarding_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/category_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/comment_article_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/like_article_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/password_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/user_article_repository_impl.dart';
import 'package:interpretasi/src/data/repositories/user_repository_impl.dart';
import 'package:interpretasi/src/domain/repositories/article_repository.dart';
import 'package:interpretasi/src/domain/repositories/auth_repository.dart';
import 'package:interpretasi/src/domain/repositories/author_data_source.dart';
import 'package:interpretasi/src/domain/repositories/boarding_repository.dart';
import 'package:interpretasi/src/domain/repositories/category_repository.dart';
import 'package:interpretasi/src/domain/repositories/comment_article_repository.dart';
import 'package:interpretasi/src/domain/repositories/like_article_repository.dart';
import 'package:interpretasi/src/domain/repositories/password_repository.dart';
import 'package:interpretasi/src/domain/repositories/user_article_repository.dart';
import 'package:interpretasi/src/domain/repositories/user_repository.dart';
import 'package:interpretasi/src/domain/usecases/article/add_view_count.dart';
import 'package:interpretasi/src/domain/usecases/article/create_article.dart';
import 'package:interpretasi/src/domain/usecases/article/delete_article.dart';
import 'package:interpretasi/src/domain/usecases/article/get_article.dart';
import 'package:interpretasi/src/domain/usecases/article/get_article_detail.dart';
import 'package:interpretasi/src/domain/usecases/article/report_article.dart';
import 'package:interpretasi/src/domain/usecases/article/update_article.dart';
import 'package:interpretasi/src/domain/usecases/article/upload_image.dart';
import 'package:interpretasi/src/domain/usecases/auth/check_google_auth.dart';
import 'package:interpretasi/src/domain/usecases/auth/resend_email_verification.dart';
import 'package:interpretasi/src/domain/usecases/auth/sign_in_with_email.dart';
import 'package:interpretasi/src/domain/usecases/auth/sign_in_with_google.dart';
import 'package:interpretasi/src/domain/usecases/auth/sign_out_with_google.dart';
import 'package:interpretasi/src/domain/usecases/auth/sign_up_with_email.dart';
import 'package:interpretasi/src/domain/usecases/author/get_author.dart';
import 'package:interpretasi/src/domain/usecases/author/report_author.dart';
import 'package:interpretasi/src/domain/usecases/category/get_categories.dart';
import 'package:interpretasi/src/domain/usecases/comment_article/delete_comment.dart';
import 'package:interpretasi/src/domain/usecases/comment_article/get_comment_list.dart';
import 'package:interpretasi/src/domain/usecases/comment_article/report_comment.dart';
import 'package:interpretasi/src/domain/usecases/comment_article/send_comment.dart';
import 'package:interpretasi/src/domain/usecases/like_article/check_like_status.dart';
import 'package:interpretasi/src/domain/usecases/like_article/like_article.dart';
import 'package:interpretasi/src/domain/usecases/on_boarding/get_boarding_list.dart';
import 'package:interpretasi/src/domain/usecases/password/add_password.dart';
import 'package:interpretasi/src/domain/usecases/password/change_password.dart';
import 'package:interpretasi/src/domain/usecases/password/forgot_password.dart';
import 'package:interpretasi/src/domain/usecases/user/check_user_verification.dart';
import 'package:interpretasi/src/domain/usecases/user/get_user_profile.dart';
import 'package:interpretasi/src/domain/usecases/user/update_user_profile.dart';
import 'package:interpretasi/src/domain/usecases/user_article/change_to_moderated.dart';
import 'package:interpretasi/src/domain/usecases/user_article/get_banned_article.dart';
import 'package:interpretasi/src/domain/usecases/user_article/get_drafted_article.dart';
import 'package:interpretasi/src/domain/usecases/user_article/get_moderated_article.dart';
import 'package:interpretasi/src/domain/usecases/user_article/get_published_article.dart';
import 'package:interpretasi/src/domain/usecases/user_article/get_rejected_article.dart';
import 'package:interpretasi/src/domain/usecases/user_article/history_article.dart';
import 'package:interpretasi/src/presentation/bloc/article/article_by_category_watcher/article_by_category_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/article_detail_watcher/article_detail_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/article_form/article_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/delete_article_actor/delete_article_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/latest_article_watcher/latest_article_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/search_article_watcher/search_article_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/trending_article_watcher/trending_article_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/upload_image_actor/upload_image_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/article/view_count_actor/view_count_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/auth/auth_watcher/auth_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/auth/sign_in_with_email_form/sign_in_with_email_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/auth/sign_in_with_google_actor/sign_in_with_google_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/auth/sign_up_with_email_form/sign_up_with_email_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/auth/verification_status_watcher/verification_status_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/author/author_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/boarding/boarding_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/category/category_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/comment_article/article_comment_watcher/article_comment_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/comment_article/delete_comment_actor/delete_comment_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/comment_article/send_comment_actor/send_comment_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/email_verification/email_verification_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/like_article_watcher/like_article_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/localization/localization_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/password/add_password_form/add_password_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/password/change_password_form/change_password_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/password/forgot_password_form/forgot_password_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/report/report_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/theme/theme_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user/user_form/user_form_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user/user_watcher/user_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/banned_watcher/banned_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/drafted_watcher/drafted_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/moderated_actor/moderated_actor_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/moderated_watcher/moderated_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/read_history_watcher/read_history_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/rejected_watcher/rejected_watcher_bloc.dart';
import 'package:interpretasi/src/presentation/bloc/user_article/user_article_published_watcher/published_watcher_bloc.dart';

final locator = GetIt.instance;
@injectableInit
void configureInjection(String env) => locator.init();

@module
abstract class RegisterModule {
  http.Client get httpClient => http.Client();
  GoogleSignIn get googleSignIn => GoogleSignIn();
}
